services:
  web:
    build:
      context: ./web
      target: prod
    environment:
      APP_NAME: "VFSC Graph"
      FLASK_APP: app/main
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "80"
      FLASK_DEBUG: "1"
      SECRET_KEY: "${SECRET_KEY}"
      CACHE_DIR: "${CACHE_DIR}"
      CACHE_TIMEOUT: "${CACHE_TIMEOUT}"
      LOGS_DIR: "${LOGS_DIR}"
      DATA_DIR: "${DATA_DIR}"
      APP_DB_FILE: "${APP_DB_FILE}"
      GRAPH_DB_FILE: "${GRAPH_DB_FILE}"
    ports:
      - "127.0.0.1:${PORT}:80"
    volumes:
      - "./data:${DATA_DIR}"
      - "./logs:${LOGS_DIR}"
      - "web_cache_data:${CACHE_DIR}"

volumes:
  web_cache_data:
